extends: substitution
message: "Use '%s' instead of '%s'."
ignorecase: true
level: error
swap:
  timeseries: time series
  kakfa: Kafka
  postgres: PostgreSQL
  PostgeSQL: PostgreSQL
  multicloud: multi-cloud
  "Aiven Kafka": "Aiven for Apache Kafka"
  "Aiven Flink": "Aiven for Apache Flink"
  "Aiven PostgreSQL": "Aiven for PostgreSQL"
  "Aiven M3": "Aiven for M3"
  "Aiven MySQL": "Aiven for MySQL"
  "Aiven Grafana": "Aiven for Grafana"
  "Aiven Redis": "Aiven for Redis"
  "Aiven Influx": "Aiven for Influx"
  "Aiven Elasticsearch": "Aiven for Elasticsearch"
  "Aiven Cassandra": "Aiven for Cassandra"
  "Aiven OpenSearch": "Aiven for OpenSearch"
  "Aiven ClickHouse": "Aiven for ClickHouse"
  "OpenSearch dashboards": "OpenSearch Dashboards"
  prometheus: Prometheus
